[workspace]
members = [
    "dmove",
    "dmove_macro",
    "muwo_search",
    "rankless_rs",
    "rankless_server",
    "rankless_trees",
]
package = { version = "0.1.0", edition = "2021" }
resolver = "2"

[profile.release]
# debug = true
# strip = false
opt-level = 3
codegen-units = 1
lto = true

[build]
rustflags = ["-C", "target-cpu=native"]
