[project]
name = "rankless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.61",
    "ccl-science-data",
    "jinja2>=3.1.6",
    "matplotlib>=3.10.8",
    "pandas[aws, parquet]>=3.0.1",
    "psycopg>=3.3.3",
    "psycopg2>=2.9.11",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.46",
    "sqlmermaid>=0.1.4",
]

[tool.uv.sources]
ccl-science-data = { path = "../../libs/ccl-science-data", editable = true }
