// Generated by wiretypes from `rankless_server::consts`; do not edit, run `make types`.

export const PORT = 3038;
// Rows one `/slice` page holds at most.
export const MAX_SLICE = 40000;
// Ids one `/metrics/:etype` request is answered for; the rest are dropped.
export const MAX_METRIC_IDS = 100;
// Pinned entities one `/slice` request is answered for; the rest are dropped.
export const MAX_PINS = 24;
// A screened ranking: the cohort's top `SCREEN_K` by citations, ranked by the sort metric.
export const SCREEN_K = 1000;
// Hex digits of the commit hash in the version stamp; `build.rs` reads the same file.
export const COMMIT_HASH_LEN = 12;
