// Generated by wiretypes from `rankless_server::responses`; do not edit, run `make types`.

import type { BiblioInfo } from '../rankless_rs/biblo_var_att';
import type { PaperScore, WorkScreen } from '../rankless_rs/metrics';
import type { AttributeLabel } from '../rankless_trees/io';
import type { Cost, ItemTexts, Kind, Param, ValueType } from '../rankless_trees/metrics';
import type { RefDAG } from '../rankless_trees/path_finder';

export type SearchResult = {
	citations: number;
	distinctText?: string;
	dmId: number;
	name: string;
	oaId: number;
	papers: number;
	rawCites?: number;
	semanticId: string;
};

export type TableRow = {
	citations: number;
	distinctText?: string;
	dmId: number;
	name: string;
	oaId: number;
	papers: number;
	rank: number | null;
	rawCites?: number;
	semanticId: string;
	values: Record<string, number>;
};

export type SliceMeta = {
	columns: string[];
	screened: number | null;
	total: number;
};

export type SliceResp = {
	meta: SliceMeta;
	rows: TableRow[];
};

export type ColumnDecl = {
	cost: Cost;
	header?: string;
	id: string;
	kind: Kind;
	label: string;
	meaning: string;
	param?: Param;
	rationale?: string;
	value: ValueType;
};

export type RootRegistry = {
	defaultSort: string;
	metrics: ColumnDecl[];
};

export type ColumnRegistry = {
	roots: Record<string, RootRegistry>;
};

export type MethodologyOut = {
	hSince: number[];
	ladderPctBands: number[];
	minTopicScore: number;
	paperScore: PaperScore;
	specCorrRate: number;
	texts: ItemTexts[];
	topHitPapers: number;
	topN: [string, number][];
	workScreen: WorkScreen;
	yearlyCounts: [number, number];
};

export type MetricValuesResp = {
	ids: number[];
	values: Record<string, (number | null)[]>;
};

export type UnionSearchResult = {
	citations: number;
	distinctText?: string;
	dmId: number;
	name: string;
	oaId: number;
	papers: number;
	rawCites?: number;
	rootType: string;
	semanticId: string;
};

export type SerializableExt = {
	authorNetwork: number[];
	relations: RelationGroups;
	startYear: number;
	yearlyCites: number[];
	yearlyPapers: number[];
};

export type RelationGroups = {
	'citing-fields': PostAttRelatedEntity[];
	'citing-topics': PostAttRelatedEntity[];
	'collab-nation': PostAttRelatedEntity[];
	'paper-authors': PostAttRelatedEntity[];
	'paper-fields': PostAttRelatedEntity[];
	'paper-journals': PostAttRelatedEntity[];
	'paper-topics': PostAttRelatedEntity[];
};

export type PostAttRelatedEntity = {
	count?: number;
	etype: string;
	name: string;
	parentName?: string;
	parentSemanticId?: string;
	score: number;
	semanticId: string;
};

export type ViewResult = {
	authorNetwork: number[];
	citations: number;
	distinctText?: string;
	dmId: number;
	meta?: Record<string, string>;
	name: string;
	oaId: number;
	papers: number;
	rawCites?: number;
	relations: RelationGroups;
	semanticId: string;
	similars: SearchResult[];
	startYear: number;
	yearlyCites: number[];
	yearlyPapers: number[];
};

export type TopResult = {
	entities: SearchResult[];
	name: string;
};

export type EntityDescription = {
	count: number;
	name: string;
};

export type CountsResponse = {
	entities: EntityDescription[];
	total_citations: number;
	total_works: number;
};

export type PeerSubfieldInfo = {
	dmId: number;
	name: string;
	semanticId: string;
};

export type PeerEntry = {
	citations: number;
	country: string | null;
	hIndex?: number;
	name: string;
	papers: number;
	semanticId: string;
	startYear: number;
	subfieldCitations: number[];
	yearCentroid?: number;
	yearlyCites: number[];
	yearlyPapers: number[];
};

export type RefSubfieldInfo = {
	papers: number;
	semanticId: string;
};

export type EntityPeersResp = {
	hero: PeerEntry;
	peers: PeerEntry[];
	refSubfields: RefSubfieldInfo[];
	topSubfields: PeerSubfieldInfo[];
};

export type LadderResp = {
	ladder: (number | null)[][];
	pctBands: number[];
};

export type StatsSubfield = {
	citations: number;
	dmId: number;
	name: string;
	semanticId: string;
};

export type YearWindow = {
	windowCitations: number;
	windowFrom: number;
	windowPapers: number;
	windowTo: number;
	yearlyCites: number[];
	yearlyPapers: number[];
};

export type StatsResp = {
	citations: number;
	dmId: number;
	eraFrom: number;
	eraTo: number;
	name: string;
	papers: number;
	semanticId: string;
	subfield?: StatsSubfield;
	topSubfields: StatsSubfield[];
	windowCitations: number;
	windowFrom: number;
	windowPapers: number;
	windowTo: number;
	yearlyCites: number[];
	yearlyPapers: number[];
};

export type ResolveWorkResp = {
	doi: string;
	name: string;
	oaId: number;
	wid: number;
	year: number;
};

export type AuthoredResp = {
	authored: boolean;
};

export type ResolveAuthorResp = {
	dmId: number;
	name: string;
	oaId: number;
	orcid?: string;
	semanticId: string;
};

export type PaperAuthorship = {
	author: string;
	insts: number[];
};

export type PaperOut = {
	authorCount: number;
	authorships: PaperAuthorship[];
	bar?: number;
	biblio?: BiblioInfo;
	citations: number;
	createdTopic?: string;
	doi: string;
	hitSemId?: string;
	isHit: boolean;
	name: string;
	oaId: number;
	score?: number;
	source: number;
	wid: number;
	year: number;
	yearlyCites?: number[];
};

export type PaperAuthorMeta = {
	prize: number;
	year: number;
};

export type PaperSetResp = {
	authorsMeta: Record<string, PaperAuthorMeta>;
	discAuthorNames: Record<string, string>;
	entityAtts: Record<string, Record<string, AttributeLabel>>;
	papers: PaperOut[];
};

export type PaginatedPaperSetResp = {
	resp: PaperSetResp;
	sliceStart: number;
	totalPapers: number;
};

export type PaperProfileResp = {
	dag: RefDAG;
	papers: PaperSetResp;
};
