use std::{
    fs,
    path::{Path, PathBuf},
};

use crate::{config::Outputs, error::Error};

/// First-line marker of every generated file; a file under an output directory without it is
/// never touched.
pub const MARKER: &str = "Generated by wiretypes";

pub fn header(module: &str, regenerate: &str) -> String {
    match module {
        "" => format!("{MARKER}; do not edit, run `{regenerate}`."),
        m => format!("{MARKER} from `{m}`; do not edit, run `{regenerate}`."),
    }
}

/// Writes every changed file and removes generated files no module renders anymore.
pub fn write(root: &Path, outputs: &Outputs) -> Result<(), Error> {
    for (dir, files) in outputs {
        let dir = root.join(dir);
        for stale in generated_files(&dir)? {
            if !files.contains_key(&stale) {
                let path = dir.join(&stale);
                fs::remove_file(&path).map_err(|e| Error::Io(path, e))?;
            }
        }
        for (rel, content) in files {
            let path = dir.join(rel);
            if fs::read_to_string(&path).ok().as_deref() == Some(content.as_str()) {
                continue;
            }
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).map_err(|e| Error::Io(parent.into(), e))?;
            }
            fs::write(&path, content).map_err(|e| Error::Io(path, e))?;
        }
    }
    Ok(())
}

/// Fails with every file that is missing, differs, or is generated but no longer rendered.
pub fn check(root: &Path, outputs: &Outputs, regenerate: &str) -> Result<(), Error> {
    let mut drift = Vec::new();
    for (dir, files) in outputs {
        let base = root.join(dir);
        for (rel, content) in files {
            match fs::read_to_string(base.join(rel)) {
                Ok(on_disk) if on_disk == *content => {}
                Ok(_) => drift.push(format!("differs: {dir}/{rel}")),
                Err(_) => drift.push(format!("missing: {dir}/{rel}")),
            }
        }
        for stale in generated_files(&base)? {
            if !files.contains_key(&stale) {
                drift.push(format!("stale: {dir}/{stale}"));
            }
        }
    }
    match drift.is_empty() {
        true => Ok(()),
        false => Err(Error::Drift {
            files: drift,
            regenerate: regenerate.to_string(),
        }),
    }
}

/// Paths, relative to `dir` and `/`-separated, of the files under it that carry [`MARKER`].
fn generated_files(dir: &Path) -> Result<Vec<String>, Error> {
    let mut out = Vec::new();
    let mut pending = vec![PathBuf::new()];
    while let Some(rel) = pending.pop() {
        let abs = dir.join(&rel);
        let entries = match fs::read_dir(&abs) {
            Ok(entries) => entries,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => continue,
            Err(e) => return Err(Error::Io(abs, e)),
        };
        for entry in entries {
            let entry = entry.map_err(|e| Error::Io(abs.clone(), e))?;
            let child = rel.join(entry.file_name());
            if entry.path().is_dir() {
                pending.push(child);
            } else if fs::read_to_string(entry.path())
                .is_ok_and(|text| text.lines().next().is_some_and(|l| l.contains(MARKER)))
            {
                out.push(child.to_string_lossy().replace('\\', "/"));
            }
        }
    }
    Ok(out)
}
