#![allow(dead_code)]

use std::collections::BTreeMap;

use crate::{config::PythonStyle, model::Model, output, python, ts, wire, WireConst, WireType};

mod shapes {
    use std::collections::HashMap;

    use serde::{Deserialize, Serialize};

    use crate::wire;

    #[wire]
    pub const LIMIT: u16 = 3;

    #[wire]
    #[derive(Serialize)]
    pub struct Base {
        pub name: Box<str>,
        #[serde(rename = "semanticId")]
        pub semantic_id: String,
        #[serde(rename = "rawCites", skip_serializing_if = "Option::is_none")]
        pub raw_cites: Option<u32>,
        pub screened: Option<usize>,
    }

    /// A row of a table.
    #[wire]
    #[derive(Serialize)]
    pub struct Row {
        #[serde(flatten)]
        pub base: Base,
        pub values: HashMap<String, f64>,
        pub span: (u16, u16),
        pub groups: Groups,
        pub tree: super::nested::TreeNode,
    }

    #[wire]
    #[derive(Serialize)]
    pub struct Groups {
        #[serde(rename = "paper-fields")]
        pub paper_fields: Vec<Base>,
    }

    #[wire]
    #[derive(Deserialize)]
    #[serde(tag = "kind", rename_all = "snake_case")]
    pub enum Payload {
        Claim { work: Option<u64> },
        Revoke,
    }

    #[wire]
    #[derive(Serialize)]
    #[serde(rename_all = "snake_case")]
    pub enum Reason {
        MissingId,
        NotInDataset,
    }
}

mod limits {
    use std::sync::LazyLock;

    use serde::Serialize;

    use crate::wire;

    /// Rows one page holds.
    #[wire]
    pub const PAGE: usize = 25;
    #[wire]
    const ROOT: &str = "/tmp/it's";
    #[wire]
    pub const BANDS: [(f64, &str); 2] = [(0.2, "top"), (0.01, "rare")];
    #[wire]
    pub const ONE: &[u8] = &[7];
    #[wire]
    pub const SCREEN: Screen = Screen {
        min: 1,
        max_rows: 20,
        span: (1951, 2026),
        kinds: &["article"],
    };
    #[wire]
    pub static ON: bool = true;
    #[wire]
    pub static BUILT: LazyLock<Screen> = LazyLock::new(|| Screen { min: 2, ..SCREEN });

    #[wire]
    #[derive(Serialize)]
    pub struct Screen {
        pub min: u8,
        #[serde(rename = "max-rows")]
        pub max_rows: u32,
        pub span: (u16, u16),
        pub kinds: &'static [&'static str],
    }
}

mod nested {
    use std::collections::HashMap;

    use serde::Serialize;

    use crate::wire;

    #[wire]
    #[derive(Serialize, Default)]
    pub struct NodeGen<T: Default> {
        #[serde(rename = "topSourceId")]
        pub top: T,
    }

    #[wire]
    pub type NodeJson = NodeGen<Option<u64>>;

    #[wire]
    #[derive(Serialize)]
    pub struct TreeNode {
        #[serde(flatten)]
        pub node: NodeJson,
        pub children: Box<Children>,
    }

    #[wire]
    #[derive(Serialize)]
    #[serde(untagged)]
    pub enum Children {
        Leaves(HashMap<u32, NodeJson>),
        Nodes(HashMap<u32, TreeNode>),
    }
}

const TS_SHAPES: &str =
    "// Generated by wiretypes from `wiretypes::tests::shapes`; do not edit, run `make types`.

import type { TreeNode } from './nested';

export const LIMIT = 3;

export type Base = {
\tname: string;
\trawCites?: number;
\tscreened: number | null;
\tsemanticId: string;
};

// A row of a table.
export type Row = {
\tgroups: Groups;
\tname: string;
\trawCites?: number;
\tscreened: number | null;
\tsemanticId: string;
\tspan: [number, number];
\ttree: TreeNode;
\tvalues: Record<string, number>;
};

export type Groups = {
\t'paper-fields': Base[];
};

export type Payload =
\t| { kind: 'claim'; work?: number | null }
\t| { kind: 'revoke' };

export type Reason = 'missing_id' | 'not_in_dataset';
";

const TS_NESTED: &str =
    "// Generated by wiretypes from `wiretypes::tests::nested`; do not edit, run `make types`.

export type NodeJson = {
\ttopSourceId: number | null;
};

export type TreeNode = {
\tchildren: Children;
\ttopSourceId: number | null;
};

export type Children = Record<string, NodeJson> | Record<string, TreeNode>;
";

const PY_SHAPES: &str =
    "# Generated by wiretypes from `wiretypes::tests::shapes`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final, Literal, NotRequired, TypedDict

from .nested import TreeNode


LIMIT: Final = 3


class Base(TypedDict):
    name: str
    rawCites: NotRequired[int]
    screened: int | None
    semanticId: str


class Row(TypedDict):
    \"\"\"A row of a table.\"\"\"
    groups: Groups
    name: str
    rawCites: NotRequired[int]
    screened: int | None
    semanticId: str
    span: tuple[int, int]
    tree: TreeNode
    values: dict[str, float]


Groups = TypedDict(
    \"Groups\",
    {
        \"paper-fields\": 'list[Base]',
    },
)


class PayloadClaim(TypedDict):
    kind: Literal[\"claim\"]
    work: NotRequired[int | None]


class PayloadRevoke(TypedDict):
    kind: Literal[\"revoke\"]


type Payload = PayloadClaim | PayloadRevoke


type Reason = Literal[\"missing_id\", \"not_in_dataset\"]
";

const TS_LIMITS: &str =
    "// Generated by wiretypes from `wiretypes::tests::limits`; do not edit, run `make types`.

// Rows one page holds.
export const PAGE = 25;
export const ROOT = '/tmp/it\\'s';
export const BANDS = [[0.2, 'top'], [0.01, 'rare']] as const;
export const ONE = [7] as const;
export const SCREEN: Screen = { kinds: ['article'], 'max-rows': 20, min: 1, span: [1951, 2026] };
export const ON = true;
export const BUILT: Screen = { kinds: ['article'], 'max-rows': 20, min: 2, span: [1951, 2026] };

export type Screen = {
\tkinds: string[];
\t'max-rows': number;
\tmin: number;
\tspan: [number, number];
};
";

const PY_LIMITS: &str =
    "# Generated by wiretypes from `wiretypes::tests::limits`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final, TypedDict


# Rows one page holds.
PAGE: Final = 25
ROOT: Final = \"/tmp/it's\"
BANDS: Final = ((0.2, \"top\"), (0.01, \"rare\"))
ONE: Final = (7,)
SCREEN: Final[Screen] = {\"kinds\": [\"article\"], \"max-rows\": 20, \"min\": 1, \"span\": (1951, 2026)}
ON: Final = True
BUILT: Final[Screen] = {\"kinds\": [\"article\"], \"max-rows\": 20, \"min\": 2, \"span\": (1951, 2026)}


Screen = TypedDict(
    \"Screen\",
    {
        \"kinds\": 'list[str]',
        \"max-rows\": 'int',
        \"min\": 'int',
        \"span\": 'tuple[int, int]',
    },
)
";

fn model() -> Model {
    Model::collect(
        inventory::iter::<WireType>(),
        inventory::iter::<WireConst>(),
    )
    .unwrap()
}

#[test]
fn typescript_spells_each_module_with_its_imports() {
    let files = ts::render(&model(), "make types").unwrap();
    assert_eq!(files["wiretypes/tests/shapes.ts"], TS_SHAPES);
    assert_eq!(files["wiretypes/tests/nested.ts"], TS_NESTED);
}

#[test]
fn values_become_literals_ahead_of_the_types() {
    let model = model();
    let ts = ts::render(&model, "make types").unwrap();
    assert_eq!(ts["wiretypes/tests/limits.ts"], TS_LIMITS);
    let py = python::render(&model, PythonStyle::TypedDict, "make types").unwrap();
    assert_eq!(py["wiretypes/tests/limits.py"], PY_LIMITS);
}

#[test]
fn python_hoists_variants_and_spells_odd_keys_functionally() {
    let files = python::render(&model(), PythonStyle::TypedDict, "make types").unwrap();
    assert_eq!(files["wiretypes/tests/shapes.py"], PY_SHAPES);
    let packages: Vec<&str> = files
        .keys()
        .map(String::as_str)
        .filter(|p| p.ends_with("__init__.py"))
        .collect();
    assert_eq!(
        packages,
        [
            "__init__.py",
            "wiretypes/__init__.py",
            "wiretypes/tests/__init__.py"
        ]
    );
}

#[test]
fn dataclasses_refuse_a_key_python_cannot_spell() {
    let err = python::render(&model(), PythonStyle::Dataclass, "make types").unwrap_err();
    assert!(
        err.to_string().contains("is not a Python identifier"),
        "{err}"
    );
}

#[test]
fn check_reports_drift_and_write_removes_stale_files() {
    let dir = std::env::temp_dir().join(format!("wiretypes-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    let render = |files: &[(&str, &str)]| -> BTreeMap<String, BTreeMap<String, String>> {
        let files = files
            .iter()
            .map(|(p, c)| (p.to_string(), c.to_string()))
            .collect();
        [("out".to_string(), files)].into()
    };
    let header = output::header("m", "make types");
    let (a, b) = (format!("// {header}\na"), format!("// {header}\nb"));
    let hand_written = dir.join("out/keep.ts");

    output::write(&dir, &render(&[("a.ts", &a), ("sub/b.ts", &b)])).unwrap();
    std::fs::write(&hand_written, "export {};\n").unwrap();
    output::check(
        &dir,
        &render(&[("a.ts", &a), ("sub/b.ts", &b)]),
        "make types",
    )
    .unwrap();

    let next = render(&[("a.ts", &b)]);
    let drift = output::check(&dir, &next, "make types")
        .unwrap_err()
        .to_string();
    assert!(
        drift.contains("differs: out/a.ts") && drift.contains("stale: out/sub/b.ts"),
        "{drift}"
    );

    output::write(&dir, &next).unwrap();
    output::check(&dir, &next, "make types").unwrap();
    assert!(hand_written.exists());
    std::fs::remove_dir_all(&dir).unwrap();
}

#[wire]
#[derive(serde::Serialize)]
struct InPackage {
    x: u8,
}
