# Generated by wiretypes from `rankless_rs::biblo_var_att`; do not edit, run `make types`.

from __future__ import annotations

from typing import TypedDict


class BiblioInfo(TypedDict):
    first_page: str
    issue: str
    last_page: str
    volume: str
