# Generated by wiretypes from `rankless_rs::derived_ledger`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final


# The env var naming the root of the data from outside OpenAlex.
EXTERNAL_DATA_ROOT: Final = "EXTERNAL_DATA_ROOT"
# The root when the variable is unset: a dev box, relative to the repo root the pipeline runs from.
DEFAULT_EXTERNAL_DATA_ROOT: Final = "data/external"
# The ORCID registry's names, under the root.
NAMES_TABLE: Final = "orcid/names.tsv.zst"
