# Generated by wiretypes from `rankless_rs::env_consts`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final


MIN_PAPERS_FOR_INST: Final = 250
MIN_PAPERS_FOR_SOURCE: Final = 200
MIN_AUTHOR_WORK_COUNT: Final = 8
MIN_AUTHOR_CITE_COUNT: Final = 400
