# Generated by wiretypes from `rankless_rs::ladder`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final


LADDER_PCT_BANDS: Final = (0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001, 0.0005, 0.0002, 0.0001)
