# Generated by wiretypes from `rankless_rs::metrics`; do not edit, run `make types`.

from __future__ import annotations

from typing import TypedDict


class PaperScore(TypedDict):
    barScale: int
    hitMultiple: float
    sfYearMinPapers: int
    topShare: float
    wSf: float
    wSfYear: float
    wYear: float


class WorkScreen(TypedDict):
    finalYear: int
    firstYear: int
    kinds: list[str]
    maxAuthorPapers: int
    maxAuthors: int
    minAuthorCitations: int
    minAuthorPapers: int
    minCitations: int
    minPapersForInstitution: int
    minPapersForSource: int


class Methodology(TypedDict):
    hSince: list[int]
    paperScore: PaperScore
    topN: list[tuple[str, int]]
    workScreen: WorkScreen


class Level(TypedDict):
    attributeType: str
    sourceSide: bool
