# Generated by wiretypes from `rankless_rs::user_ledger`; do not edit, run `make types`.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class SkippedEvent(TypedDict):
    key: str
    reason: SkipReason


class WorkSubject(TypedDict):
    """A work as a ledger event names it, written by the site and by `pyscripts/ledger_ids.py`. The
    pipeline reads `oa_id` and `doi`, so a line carrying only those parses."""
    display_snapshot: WorkSnapshot
    dm_id_at_creation: int | None
    doi: str | None
    oa_id: int | None
    run_id_at_creation: str | None
    semantic_id_at_creation: str | None


class AuthorSubject(TypedDict):
    """An author record as a ledger event names it; the pipeline reads `oa_id`."""
    display_snapshot: AuthorSnapshot
    dm_id_at_creation: int | None
    oa_id: int | None
    orcid: str | None
    run_id_at_creation: str | None
    semantic_id_at_creation: str | None


class WorkSnapshot(TypedDict):
    """What the claimant saw of a work when creating the event."""
    title: str
    year: int | None


class AuthorSnapshot(TypedDict):
    display_name: str


class AppliedManifest(TypedDict):
    """`applied_manifest.json`, read by the site: what the run applied and why it skipped the rest,
    events named by their logical key."""
    applied_keys: list[str]
    run_id: str
    skipped: list[SkippedEvent]
    snapshot_at: str


type SkipReason = Literal["missing_oa_id", "missing_oa_id_or_orcid", "orcid_not_in_dataset", "oa_id_not_in_dataset", "doi_not_in_snapshot", "claimant_not_attributed"]


class EventPayloadMergeAuthors(TypedDict):
    kind: Literal["merge_authors"]
    drop: AuthorSubject
    keep: AuthorSubject
    note: NotRequired[str]


class EventPayloadMergePapers(TypedDict):
    kind: Literal["merge_papers"]
    drop: WorkSubject
    keep: WorkSubject


class EventPayloadDisownPaper(TypedDict):
    kind: Literal["disown_paper"]
    work: WorkSubject


class EventPayloadClaimPaper(TypedDict):
    kind: Literal["claim_paper"]
    work: WorkSubject


class EventPayloadStripOrcid(TypedDict):
    kind: Literal["strip_orcid"]
    author: AuthorSubject


class EventPayloadRevoke(TypedDict):
    kind: Literal["revoke"]
    reason: NotRequired[str]
    # The revoked event's logical key, which a DB merge leaves stable (an event_id is
    # renumbered).
    target_key: str


class EventPayloadModerationDecision(TypedDict):
    kind: Literal["moderation_decision"]
    decision: ModerationVerdict
    reason: NotRequired[str]
    target_event_id: int


class EventPayloadAddPaperRequest(TypedDict):
    kind: Literal["add_paper_request"]
    work_claim: dict[str, Any]


# What a ledger event does, as the site stores it and `active.jsonl` carries it; `kind` is the
# tag.
type EventPayload = EventPayloadMergeAuthors | EventPayloadMergePapers | EventPayloadDisownPaper | EventPayloadClaimPaper | EventPayloadStripOrcid | EventPayloadRevoke | EventPayloadModerationDecision | EventPayloadAddPaperRequest


type ModerationVerdict = Literal["accepted", "rejected"]
