# Generated by wiretypes from `rankless_rs::user_ledger`; do not edit, run `make types`.

from __future__ import annotations

from typing import Any, Final, Literal, NotRequired, TypedDict


# The derived source's manifest, written beside its records.
DERIVED_MANIFEST: Final = "derived_manifest.json"
# The team's curated events, copied beside the site's by `export_user_ledger.py`.
CURATED_JSONL: Final = "curated.jsonl"
# The site's active events, one per line, as the export writes them.
ACTIVE_JSONL: Final = "active.jsonl"
# The export's run id, event ids and events per source.
SNAPSHOT_MANIFEST: Final = "snapshot_manifest.json"
# The pinned owners' ORCIDs, one per line.
OWNER_PINS: Final = "owner_pins.txt"
# What the filter step applied and skipped of the ledger, read by the site.
APPLIED_MANIFEST: Final = "applied_manifest.json"
# The filter step's private sidecar: the forced œuvre's aggregates and forced-only work ids.
FORCED_WORKS: Final = "forced_works.json"


class SkippedEvent(TypedDict):
    key: str
    reason: SkipReason


class WorkSubject(TypedDict):
    """A work as a ledger event names it, written by the site and by `pyscripts/ledger_ids.py`. The
    pipeline reads `oa_id` and `doi`, so a line carrying only those parses."""
    display_snapshot: WorkSnapshot
    dm_id_at_creation: int | None
    doi: str | None
    oa_id: int | None
    run_id_at_creation: str | None
    semantic_id_at_creation: str | None


class AuthorSubject(TypedDict):
    """An author record as a ledger event names it; the pipeline reads `oa_id`."""
    display_snapshot: AuthorSnapshot
    dm_id_at_creation: int | None
    oa_id: int | None
    orcid: str | None
    run_id_at_creation: str | None
    semantic_id_at_creation: str | None


class WorkSnapshot(TypedDict):
    """What the claimant saw of a work when creating the event."""
    title: str
    year: int | None


class AuthorSnapshot(TypedDict):
    display_name: str


class AppliedManifest(TypedDict):
    """`APPLIED_MANIFEST`, read by the site: what the run applied and why it skipped the rest,
    events named by their logical key."""
    applied_keys: list[str]
    run_id: str
    skipped: list[SkippedEvent]
    snapshot_at: str


type SkipReason = Literal["missing_oa_id", "missing_oa_id_or_orcid", "orcid_not_in_dataset", "oa_id_not_in_dataset", "doi_not_in_snapshot", "claimant_not_attributed", "author_not_on_work", "work_screened", "superseded", "merge_cycle"]


class EventPayloadMergeAuthors(TypedDict):
    kind: Literal["merge_authors"]
    drop: AuthorSubject
    keep: AuthorSubject
    note: NotRequired[str]


class EventPayloadMergePapers(TypedDict):
    kind: Literal["merge_papers"]
    drop: WorkSubject
    keep: WorkSubject


class EventPayloadDisownPaper(TypedDict):
    kind: Literal["disown_paper"]
    work: WorkSubject


class EventPayloadClaimPaper(TypedDict):
    kind: Literal["claim_paper"]
    work: WorkSubject


class EventPayloadStripOrcid(TypedDict):
    kind: Literal["strip_orcid"]
    author: AuthorSubject


class EventPayloadReassignPaper(TypedDict):
    kind: Literal["reassign_paper"]
    author: AuthorSubject
    to: NotRequired[AuthorSubject]
    work: WorkSubject


class EventPayloadNameAuthor(TypedDict):
    kind: Literal["name_author"]
    author: AuthorSubject
    name: str


class EventPayloadRevoke(TypedDict):
    kind: Literal["revoke"]
    reason: NotRequired[str]
    # The revoked event's logical key, which a DB merge leaves stable (an event_id is
    # renumbered).
    target_key: str


class EventPayloadModerationDecision(TypedDict):
    kind: Literal["moderation_decision"]
    decision: ModerationVerdict
    reason: NotRequired[str]
    target_event_id: int


class EventPayloadAddPaperRequest(TypedDict):
    kind: Literal["add_paper_request"]
    work_claim: dict[str, Any]


# What a ledger event does, as the site stores it and `ACTIVE_JSONL` carries it; `kind` is the
# tag.
type EventPayload = EventPayloadMergeAuthors | EventPayloadMergePapers | EventPayloadDisownPaper | EventPayloadClaimPaper | EventPayloadStripOrcid | EventPayloadReassignPaper | EventPayloadNameAuthor | EventPayloadRevoke | EventPayloadModerationDecision | EventPayloadAddPaperRequest


type ModerationVerdict = Literal["accepted", "rejected"]
