// Generated by wiretypes from `rankless_rs::derived_ledger`; do not edit, run `make types`.

// The env var naming the root of the data from outside OpenAlex.
export const EXTERNAL_DATA_ROOT = 'EXTERNAL_DATA_ROOT';
// The root when the variable is unset: a dev box, relative to the repo root the pipeline runs from.
export const DEFAULT_EXTERNAL_DATA_ROOT = 'data/external';
// The ORCID registry's names, under the root.
export const NAMES_TABLE = 'orcid/names.tsv.zst';
