// Generated by wiretypes from `rankless_rs::env_consts`; do not edit, run `make types`.

export const MIN_PAPERS_FOR_INST = 250;
export const MIN_PAPERS_FOR_SOURCE = 200;
export const MIN_AUTHOR_WORK_COUNT = 8;
export const MIN_AUTHOR_CITE_COUNT = 400;
