// Generated by wiretypes from `rankless_rs::ladder`; do not edit, run `make types`.

export const LADDER_PCT_BANDS = [0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001, 0.0005, 0.0002, 0.0001] as const;
