// Generated by wiretypes from `rankless_rs::metrics`; do not edit, run `make types`.

export type PaperScore = {
	barScale: number;
	hitMultiple: number;
	sfYearMinPapers: number;
	topShare: number;
	wSf: number;
	wSfYear: number;
	wYear: number;
};

export type WorkScreen = {
	finalYear: number;
	firstYear: number;
	kinds: string[];
	maxAuthorPapers: number;
	maxAuthors: number;
	minAuthorCitations: number;
	minAuthorPapers: number;
	minCitations: number;
	minPapersForInstitution: number;
	minPapersForSource: number;
};

export type Methodology = {
	hSince: number[];
	paperScore: PaperScore;
	topN: [string, number][];
	workScreen: WorkScreen;
};

export type Level = {
	attributeType: string;
	sourceSide: boolean;
};
