// Generated by wiretypes from `rankless_rs::metrics`; do not edit, run `make types`.

export const PAPER_SCORE: PaperScore = { barScale: 4, hitMultiple: 1.5, sfYearMinPapers: 400, topShare: 0.01, wSf: 0.005, wSfYear: 0.895, wYear: 0.1 };
export const TOP_N = [['sources', 1000], ['institutions', 2000], ['countries', 2000], ['authors', 20]] as const;
export const MIN_TOPIC_SCORE = 0.7;
export const TOP_HIT_PAPERS = 50;
export const MAX_SHARED_PAPERS = 251;
export const SPEC_CORR_RATE = 0.45;

export type PaperScore = {
	barScale: number;
	hitMultiple: number;
	sfYearMinPapers: number;
	topShare: number;
	wSf: number;
	wSfYear: number;
	wYear: number;
};

export type WorkScreen = {
	abstractDoiPrefixes: string[];
	finalYear: number;
	firstYear: number;
	kinds: string[];
	maxAuthorPapers: number;
	minCitations: number;
	teamLimit: number;
};

export type Methodology = {
	hSince: number[];
	ladderPctBands: number[];
	minTopicScore: number;
	paperScore: PaperScore;
	specCorrRate: number;
	topHitPapers: number;
	topN: [string, number][];
	workScreen: WorkScreen;
};

export type Level = {
	attributeType: string;
	sourceSide: boolean;
};
