// Generated by wiretypes from `rankless_rs::user_ledger`; do not edit, run `make types`.

export type SkippedEvent = {
	key: string;
	reason: SkipReason;
};

// A work as a ledger event names it, written by the site and by `pyscripts/ledger_ids.py`. The
// pipeline reads `oa_id` and `doi`, so a line carrying only those parses.
export type WorkSubject = {
	display_snapshot: WorkSnapshot;
	dm_id_at_creation: number | null;
	doi: string | null;
	oa_id: number | null;
	run_id_at_creation: string | null;
	semantic_id_at_creation: string | null;
};

// An author record as a ledger event names it; the pipeline reads `oa_id`.
export type AuthorSubject = {
	display_snapshot: AuthorSnapshot;
	dm_id_at_creation: number | null;
	oa_id: number | null;
	orcid: string | null;
	run_id_at_creation: string | null;
	semantic_id_at_creation: string | null;
};

// What the claimant saw of a work when creating the event.
export type WorkSnapshot = {
	title: string;
	year: number | null;
};

export type AuthorSnapshot = {
	display_name: string;
};

// `applied_manifest.json`, read by the site: what the run applied and why it skipped the rest,
// events named by their logical key.
export type AppliedManifest = {
	applied_keys: string[];
	run_id: string;
	skipped: SkippedEvent[];
	snapshot_at: string;
};

export type SkipReason = 'missing_oa_id' | 'missing_oa_id_or_orcid' | 'orcid_not_in_dataset' | 'oa_id_not_in_dataset' | 'doi_not_in_snapshot' | 'claimant_not_attributed';

// What a ledger event does, as the site stores it and `active.jsonl` carries it; `kind` is the
// tag.
export type EventPayload =
	| { kind: 'merge_authors'; drop: AuthorSubject; keep: AuthorSubject; note?: string }
	| { kind: 'merge_papers'; drop: WorkSubject; keep: WorkSubject }
	| { kind: 'disown_paper'; work: WorkSubject }
	| { kind: 'claim_paper'; work: WorkSubject }
	| { kind: 'strip_orcid'; author: AuthorSubject }
	| { kind: 'revoke'; reason?: string; target_key: string }
	| { kind: 'moderation_decision'; decision: ModerationVerdict; reason?: string; target_event_id: number }
	| { kind: 'add_paper_request'; work_claim: Record<string, unknown> };

export type ModerationVerdict = 'accepted' | 'rejected';
