// Generated by wiretypes from `rankless_rs::user_ledger`; do not edit, run `make types`.

// The derived source's manifest, written beside its records.
export const DERIVED_MANIFEST = 'derived_manifest.json';
// The team's curated events, copied beside the site's by `export_user_ledger.py`.
export const CURATED_JSONL = 'curated.jsonl';
// The site's active events, one per line, as the export writes them.
export const ACTIVE_JSONL = 'active.jsonl';
// The export's run id, event ids and events per source.
export const SNAPSHOT_MANIFEST = 'snapshot_manifest.json';
// The pinned owners' ORCIDs, one per line.
export const OWNER_PINS = 'owner_pins.txt';
// What the filter step applied and skipped of the ledger, read by the site.
export const APPLIED_MANIFEST = 'applied_manifest.json';
// The filter step's private sidecar: the forced œuvre's aggregates and forced-only work ids.
export const FORCED_WORKS = 'forced_works.json';

export type SkippedEvent = {
	key: string;
	reason: SkipReason;
};

// A work as a ledger event names it, written by the site and by `pyscripts/ledger_ids.py`. The
// pipeline reads `oa_id` and `doi`, so a line carrying only those parses.
export type WorkSubject = {
	display_snapshot: WorkSnapshot;
	dm_id_at_creation: number | null;
	doi: string | null;
	oa_id: number | null;
	run_id_at_creation: string | null;
	semantic_id_at_creation: string | null;
};

// An author record as a ledger event names it; the pipeline reads `oa_id`.
export type AuthorSubject = {
	display_snapshot: AuthorSnapshot;
	dm_id_at_creation: number | null;
	oa_id: number | null;
	orcid: string | null;
	run_id_at_creation: string | null;
	semantic_id_at_creation: string | null;
};

// What the claimant saw of a work when creating the event.
export type WorkSnapshot = {
	title: string;
	year: number | null;
};

export type AuthorSnapshot = {
	display_name: string;
};

// `APPLIED_MANIFEST`, read by the site: what the run applied and why it skipped the rest,
// events named by their logical key.
export type AppliedManifest = {
	applied_keys: string[];
	run_id: string;
	skipped: SkippedEvent[];
	snapshot_at: string;
};

export type SkipReason = 'missing_oa_id' | 'missing_oa_id_or_orcid' | 'orcid_not_in_dataset' | 'oa_id_not_in_dataset' | 'doi_not_in_snapshot' | 'claimant_not_attributed' | 'author_not_on_work' | 'work_screened' | 'superseded' | 'merge_cycle';

// What a ledger event does, as the site stores it and `ACTIVE_JSONL` carries it; `kind` is the
// tag.
export type EventPayload =
	| { kind: 'merge_authors'; drop: AuthorSubject; keep: AuthorSubject; note?: string }
	| { kind: 'merge_papers'; drop: WorkSubject; keep: WorkSubject }
	| { kind: 'disown_paper'; work: WorkSubject }
	| { kind: 'claim_paper'; work: WorkSubject }
	| { kind: 'strip_orcid'; author: AuthorSubject }
	| { kind: 'reassign_paper'; author: AuthorSubject; to?: AuthorSubject; work: WorkSubject }
	| { kind: 'name_author'; author: AuthorSubject; name: string }
	| { kind: 'revoke'; reason?: string; target_key: string }
	| { kind: 'moderation_decision'; decision: ModerationVerdict; reason?: string; target_event_id: number }
	| { kind: 'add_paper_request'; work_claim: Record<string, unknown> };

export type ModerationVerdict = 'accepted' | 'rejected';
