// Generated by wiretypes from `rankless_trees::io`; do not edit, run `make types`.

export type TreeSpecMap = Record<string, TreeSpec[]>;

export type AttributeLabels = Record<string, Record<string, AttributeLabelOut>>;

export type EntityAttsForLinks = Record<string, Record<string, AttributeLabel>>;

export type CollapsedNodeJson = {
	linkCount: number;
	sourceCount: number;
	topSourceId: number | null;
	topSourceLinks: number;
};

export type AttributeLabel = {
	name: string;
	semantic_id: string;
	spec_baseline: number;
};

export type AttributeLabelOut = {
	name: string;
	oaId?: number;
	specBaseline: number;
};

export type JsSerTree = {
	children: JsSerChildren;
	linkCount: number;
	sourceCount: number;
	topSourceId: number | null;
	topSourceLinks: number;
};

export type TreeResponse = {
	atts: Record<string, Record<string, AttributeLabelOut>>;
	shallowed: boolean;
	tree: JsSerTree;
};

export type TreeSpecs = {
	specs: Record<string, TreeSpec[]>;
	yearBreaks: number[];
};

export type TreeSpec = {
	allowSpec: boolean;
	breakdowns: BreakdownSpec[];
	defaultIsSpec: boolean;
	defaultYear: number;
	rootType: string;
};

export type BreakdownSpec = {
	attributeType: string;
	sourceSide: boolean;
	specDenomInd: number;
};

export type JsSerChildren = Record<string, CollapsedNodeJson> | Record<string, JsSerTree>;
