// Generated by wiretypes from `rankless_trees::metrics`; do not edit, run `make types`.

export type ItemTexts = {
	header?: string;
	id: string;
	label: string;
	meaning: string;
	rationale?: string;
};

export type MetricTexts = {
	header?: string;
	label: string;
	meaning: string;
	rationale?: string;
};

export type Kind = 'global' | 'intricate';

export type Cost = 'read' | 'walk';

export type ValueType =
	| { type: 'count' }
	| { type: 'score' }
	| { type: 'share' }
	| { type: 'year' }
	| { type: 'entity'; entity: string }
	| { type: 'entities'; entity: string };

export type Param = 'subfield' | 'country' | 'window';
