// Generated by wiretypes from `rankless_trees::part_iterator`; do not edit, run `make types`.

// The env var naming where tree parts spill.
export const PARTS_ROOT_VAR = 'RANKLESS_PARTS_ROOT';
// Where tree parts spill when the var is unset or empty.
export const DEFAULT_PARTS_ROOT = '/tmp/dmove-parts';
