// Generated by wiretypes from `rankless_trees::path_finder`; do not edit, run `make types`.

export type RefDAGNodeT = Record<string, RefDAG>;

export type RefDAG =
	| 'Leaf'
	| { Node: Record<string, RefDAG> };
