"""Run one or more reasoning paths over the collected entity evidence.

    uv run -m pyscripts.explore [--paths bugs,features,stories] \
        [--model sonnet|opus] [--sample N]

`--paths all` (default) runs every path. Each path samples the wide snapshot set
independently (per-module SAMPLE; --sample overrides for all). Every path's
section is merged into a single report (logs/explore-report.md); the bugs path's
draft ledger suggestions go to logs/explore-suggestions.jsonl. Exit code is 1 if
any path reports a critical finding or errors.
"""

import argparse
import json
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

from pyscripts.explore import REPORT_PATH, SUGGESTIONS_PATH, PathResult, cli, evidence
from pyscripts.explore.paths import REGISTRY


def main() -> int:
    parser = argparse.ArgumentParser(description="Rankless agent reasoning paths.")
    parser.add_argument(
        "--paths",
        default="all",
        help=f"comma list of {','.join(REGISTRY)} (or 'all', default).",
    )
    parser.add_argument(
        "--model",
        default=cli.DEFAULT_MODEL,
        help=(
            f"Review model: '{'|'.join(cli.MODELS)}' shortcut "
            f"(default: {cli.DEFAULT_MODEL}) or any full Claude model id."
        ),
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=None,
        help="Random per-path entity sample size; overrides each path's default.",
    )
    args = parser.parse_args()

    selected = list(REGISTRY) if args.paths in ("", "all") else _split(args.paths)
    unknown = [p for p in selected if p not in REGISTRY]
    if unknown:
        print(f"ERROR: unknown path(s) {unknown}; choose from {list(REGISTRY)}.")
        return 2

    model = cli.resolve_model(args.model)
    try:
        snapshots = evidence.load_snapshots()
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1

    print(
        f"Running {len(selected)} path(s) over {len(snapshots)} collected "
        f"entities with {model}: {', '.join(selected)}"
    )
    # Each path samples independently, then runs concurrently (independent CLI
    # calls — wall time is the slowest path, not their sum).
    plan = []
    for name in selected:
        module = REGISTRY[name]
        n = args.sample if args.sample is not None else getattr(module, "SAMPLE", None)
        plan.append((name, module, evidence.sample_snapshots(snapshots, n)))

    exit_code = 0
    by_name: dict[str, PathResult] = {}
    with ThreadPoolExecutor(max_workers=len(plan)) as pool:
        futures = {
            pool.submit(mod.run, subset, model): name for name, mod, subset in plan
        }
        for future in as_completed(futures):
            name = futures[future]
            try:
                by_name[name] = future.result()
            except (RuntimeError, ValueError, KeyError) as exc:
                print(f"[{name}] ERROR: {exc}")
                exit_code = 1

    results = [by_name[n] for n in selected if n in by_name]
    exit_code = max([exit_code, *(r.exit_code for r in results)])
    _write_outputs(results, model, len(snapshots), selected)
    return exit_code


def _write_outputs(
    results: list[PathResult], model: str, n_entities: int, selected: list[str]
) -> None:
    suggestions = [s for r in results for s in r.suggestions]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(
        _report(results, model, n_entities, selected, len(suggestions))
    )
    if suggestions:
        SUGGESTIONS_PATH.write_text("".join(json.dumps(s) + "\n" for s in suggestions))
    elif SUGGESTIONS_PATH.exists():
        SUGGESTIONS_PATH.unlink()
    print(f"-> {REPORT_PATH}" + (f", {SUGGESTIONS_PATH}" if suggestions else ""))


def _report(
    results: list[PathResult],
    model: str,
    n_entities: int,
    selected: list[str],
    n_sug: int,
) -> str:
    out = [
        "# Rankless explore report",
        "",
        f"_Generated by `{model}` over `logs/sanity_check_data.json` "
        f"({n_entities} entities collected). Paths: {', '.join(selected)}._",
        "",
    ]
    if n_sug:
        out += [
            f"{n_sug} draft data-edit suggestion(s) in `{SUGGESTIONS_PATH}` — "
            "user-submit `LedgerPayload` format (`src/lib/types/ledger.ts`); ids are "
            "deferred for tier-1 resolution (`.cril/ideas.md` §3) before submitting.",
            "",
        ]
    for result in results:
        out += [result.section, "", "---", ""]
    return "\n".join(out).rstrip() + "\n"


def _split(raw: str) -> list[str]:
    return [p.strip() for p in raw.split(",") if p.strip()]


if __name__ == "__main__":
    sys.exit(main())
