# Generated by wiretypes from `rankless_trees::io`; do not edit, run `make types`.

from __future__ import annotations

from typing import NotRequired, TypedDict


type TreeSpecMap = dict[str, list[TreeSpec]]


type AttributeLabels = dict[str, dict[str, AttributeLabelOut]]


type EntityAttsForLinks = dict[str, dict[str, AttributeLabel]]


class CollapsedNodeJson(TypedDict):
    linkCount: int
    sourceCount: int
    topSourceId: int | None
    topSourceLinks: int


class AttributeLabel(TypedDict):
    name: str
    semantic_id: str
    spec_baseline: float


class AttributeLabelOut(TypedDict):
    name: str
    oaId: NotRequired[int]
    specBaseline: float


class JsSerTree(TypedDict):
    children: JsSerChildren
    linkCount: int
    sourceCount: int
    topSourceId: int | None
    topSourceLinks: int


class TreeResponse(TypedDict):
    atts: dict[str, dict[str, AttributeLabelOut]]
    shallowed: bool
    tree: JsSerTree


class TreeSpecs(TypedDict):
    specs: dict[str, list[TreeSpec]]
    yearBreaks: list[int]


class TreeSpec(TypedDict):
    allowSpec: bool
    breakdowns: list[BreakdownSpec]
    defaultIsSpec: bool
    defaultYear: int
    rootType: str


class BreakdownSpec(TypedDict):
    attributeType: str
    sourceSide: bool
    specDenomInd: int


type JsSerChildren = dict[str, CollapsedNodeJson] | dict[str, JsSerTree]
