# Generated by wiretypes from `rankless_trees::metrics`; do not edit, run `make types`.

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class ItemTexts(TypedDict):
    header: NotRequired[str]
    id: str
    label: str
    meaning: str
    rationale: NotRequired[str]


class MetricTexts(TypedDict):
    header: NotRequired[str]
    label: str
    meaning: str
    rationale: NotRequired[str]


type Kind = Literal["global", "intricate"]


type Cost = Literal["read", "walk"]


class ValueTypeCount(TypedDict):
    type: Literal["count"]


class ValueTypeScore(TypedDict):
    type: Literal["score"]


class ValueTypeShare(TypedDict):
    type: Literal["share"]


class ValueTypeYear(TypedDict):
    type: Literal["year"]


class ValueTypeEntity(TypedDict):
    type: Literal["entity"]
    entity: str


class ValueTypeEntities(TypedDict):
    type: Literal["entities"]
    entity: str


type ValueType = ValueTypeCount | ValueTypeScore | ValueTypeShare | ValueTypeYear | ValueTypeEntity | ValueTypeEntities


type Param = Literal["subfield", "country", "window"]
