# Generated by wiretypes from `rankless_trees::part_iterator`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final


# The env var naming where tree parts spill.
PARTS_ROOT_VAR: Final = "RANKLESS_PARTS_ROOT"
# Where tree parts spill when the var is unset or empty.
DEFAULT_PARTS_ROOT: Final = "/tmp/dmove-parts"
