# Generated by wiretypes from `rankless_trees::path_finder`; do not edit, run `make types`.

from __future__ import annotations

from typing import Literal, TypedDict


type RefDAGNodeT = dict[str, RefDAG]


class RefDAGNode(TypedDict):
    Node: dict[str, RefDAG]


type RefDAG = Literal["Leaf"] | RefDAGNode
