# Generated by wiretypes from `rankless_server::consts`; do not edit, run `make types`.

from __future__ import annotations

from typing import Final


PORT: Final = 3038
# Rows one `/slice` page holds at most.
MAX_SLICE: Final = 40000
# Ids one `/metrics/:etype` request is answered for; the rest are dropped.
MAX_METRIC_IDS: Final = 100
# Pinned entities one `/slice` request is answered for; the rest are dropped.
MAX_PINS: Final = 24
# A screened ranking: the cohort's top `SCREEN_K` by citations, ranked by the sort metric.
SCREEN_K: Final = 1000
# Hex digits of the commit hash in the version stamp; `build.rs` reads the same file.
COMMIT_HASH_LEN: Final = 12
