# Generated by wiretypes from `rankless_server::responses`; do not edit, run `make types`.

from __future__ import annotations

from typing import NotRequired, TypedDict

from ..rankless_rs.biblo_var_att import BiblioInfo
from ..rankless_rs.metrics import PaperScore, WorkScreen
from ..rankless_trees.io import AttributeLabel
from ..rankless_trees.metrics import Cost, ItemTexts, Kind, Param, ValueType
from ..rankless_trees.path_finder import RefDAG


class SearchResult(TypedDict):
    citations: int
    distinctText: NotRequired[str]
    dmId: int
    name: str
    oaId: int
    papers: int
    rawCites: NotRequired[int]
    semanticId: str


class TableRow(TypedDict):
    citations: int
    distinctText: NotRequired[str]
    dmId: int
    name: str
    oaId: int
    papers: int
    rank: int | None
    rawCites: NotRequired[int]
    semanticId: str
    values: dict[str, float]


class SliceMeta(TypedDict):
    columns: list[str]
    screened: int | None
    total: int


class SliceResp(TypedDict):
    meta: SliceMeta
    rows: list[TableRow]


class ColumnDecl(TypedDict):
    cost: Cost
    header: NotRequired[str]
    id: str
    kind: Kind
    label: str
    meaning: str
    param: NotRequired[Param]
    rationale: NotRequired[str]
    value: ValueType


class RootRegistry(TypedDict):
    defaultSort: str
    metrics: list[ColumnDecl]


class ColumnRegistry(TypedDict):
    roots: dict[str, RootRegistry]


class MethodologyOut(TypedDict):
    hSince: list[int]
    paperScore: PaperScore
    texts: list[ItemTexts]
    topN: list[tuple[str, int]]
    workScreen: WorkScreen
    yearlyCounts: tuple[int, int]


class MetricValuesResp(TypedDict):
    ids: list[int]
    values: dict[str, list[float | None]]


class UnionSearchResult(TypedDict):
    citations: int
    distinctText: NotRequired[str]
    dmId: int
    name: str
    oaId: int
    papers: int
    rawCites: NotRequired[int]
    rootType: str
    semanticId: str


class SerializableExt(TypedDict):
    authorNetwork: list[int]
    relations: RelationGroups
    startYear: int
    yearlyCites: list[int]
    yearlyPapers: list[int]


RelationGroups = TypedDict(
    "RelationGroups",
    {
        "citing-fields": 'list[PostAttRelatedEntity]',
        "citing-topics": 'list[PostAttRelatedEntity]',
        "collab-nation": 'list[PostAttRelatedEntity]',
        "paper-authors": 'list[PostAttRelatedEntity]',
        "paper-fields": 'list[PostAttRelatedEntity]',
        "paper-journals": 'list[PostAttRelatedEntity]',
        "paper-topics": 'list[PostAttRelatedEntity]',
    },
)


class PostAttRelatedEntity(TypedDict):
    count: NotRequired[int]
    etype: str
    name: str
    parentName: NotRequired[str]
    parentSemanticId: NotRequired[str]
    score: int
    semanticId: str


class ViewResult(TypedDict):
    authorNetwork: list[int]
    citations: int
    distinctText: NotRequired[str]
    dmId: int
    meta: NotRequired[dict[str, str]]
    name: str
    oaId: int
    papers: int
    rawCites: NotRequired[int]
    relations: RelationGroups
    semanticId: str
    similars: list[SearchResult]
    startYear: int
    yearlyCites: list[int]
    yearlyPapers: list[int]


class TopResult(TypedDict):
    entities: list[SearchResult]
    name: str


class EntityDescription(TypedDict):
    count: int
    name: str


class CountsResponse(TypedDict):
    entities: list[EntityDescription]
    total_citations: int
    total_works: int


class PeerSubfieldInfo(TypedDict):
    dmId: int
    name: str
    semanticId: str


class PeerEntry(TypedDict):
    citations: int
    country: str | None
    hIndex: NotRequired[int]
    name: str
    papers: int
    semanticId: str
    startYear: int
    subfieldCitations: list[int]
    yearCentroid: NotRequired[float]
    yearlyCites: list[int]
    yearlyPapers: list[int]


class RefSubfieldInfo(TypedDict):
    papers: int
    semanticId: str


class EntityPeersResp(TypedDict):
    hero: PeerEntry
    peers: list[PeerEntry]
    refSubfields: list[RefSubfieldInfo]
    topSubfields: list[PeerSubfieldInfo]


class LadderResp(TypedDict):
    ladder: list[list[int | None]]
    pctBands: list[float]


class StatsSubfield(TypedDict):
    citations: int
    dmId: int
    name: str
    semanticId: str


class YearWindow(TypedDict):
    windowCitations: int
    windowFrom: int
    windowPapers: int
    windowTo: int
    yearlyCites: list[int]
    yearlyPapers: list[int]


class StatsResp(TypedDict):
    citations: int
    dmId: int
    eraFrom: int
    eraTo: int
    name: str
    papers: int
    semanticId: str
    subfield: NotRequired[StatsSubfield]
    topSubfields: list[StatsSubfield]
    windowCitations: int
    windowFrom: int
    windowPapers: int
    windowTo: int
    yearlyCites: list[int]
    yearlyPapers: list[int]


class ResolveWorkResp(TypedDict):
    doi: str
    name: str
    oaId: int
    wid: int
    year: int


class AuthoredResp(TypedDict):
    authored: bool


class ResolveAuthorResp(TypedDict):
    dmId: int
    name: str
    oaId: int
    orcid: NotRequired[str]
    semanticId: str


class PaperAuthorship(TypedDict):
    author: str
    insts: list[int]


class PaperOut(TypedDict):
    authorCount: int
    authorships: list[PaperAuthorship]
    bar: NotRequired[float]
    biblio: NotRequired[BiblioInfo]
    citations: int
    createdTopic: NotRequired[str]
    doi: str
    hitSemId: NotRequired[str]
    isHit: bool
    name: str
    oaId: int
    score: NotRequired[float]
    source: int
    wid: int
    year: int
    yearlyCites: NotRequired[list[int]]


class PaperAuthorMeta(TypedDict):
    prize: int
    year: int


class PaperSetResp(TypedDict):
    authorsMeta: dict[str, PaperAuthorMeta]
    discAuthorNames: dict[str, str]
    entityAtts: dict[str, dict[str, AttributeLabel]]
    papers: list[PaperOut]


class PaginatedPaperSetResp(TypedDict):
    resp: PaperSetResp
    sliceStart: int
    totalPapers: int


class PaperProfileResp(TypedDict):
    dag: RefDAG
    papers: PaperSetResp
