# Generated by wiretypes from `rankless_expr`; do not edit, run `make types`.

from __future__ import annotations

from typing import Literal, TypedDict


class ExprClause(TypedDict):
    clause: Clause


ExprAnd = TypedDict(
    "ExprAnd",
    {
        "and": 'list[Expr]',
    },
)


ExprOr = TypedDict(
    "ExprOr",
    {
        "or": 'list[Expr]',
    },
)


ExprNot = TypedDict(
    "ExprNot",
    {
        "not": 'Expr',
    },
)


type Expr = ExprClause | ExprAnd | ExprOr | ExprNot


class Clause(TypedDict):
    call: Call
    op: Op
    operand: Operand


class Call(TypedDict):
    args: list[Arg]
    metric: str


type Arg = float | str


type Op = Literal["eq", "ne", "lt", "le", "gt", "ge", "in", "not_in"]


type Operand = float | str | list[Arg]
