// Generated by wiretypes from `rankless_expr`; do not edit, run `make types`.

export type Expr =
	| { clause: Clause }
	| { and: Expr[] }
	| { or: Expr[] }
	| { not: Expr };

export type Clause = {
	call: Call;
	op: Op;
	operand: Operand;
};

export type Call = {
	args: Arg[];
	metric: string;
};

export type Arg = number | string;

export type Op = 'eq' | 'ne' | 'lt' | 'le' | 'gt' | 'ge' | 'in' | 'not_in';

export type Operand = number | string | Arg[];
