"""Check that the ccl-science-data reader still parses the generated dmove entities.

    uv run -m pyscripts.typeaudit [--strict]   # make type-audit

Runs ccl's own `_parse_entities` over `rankless_rs/src/gen/` and compares what it
finds against a format-tolerant ground truth, writes logs/type-audit.md and prints
a summary. Exits nonzero when the parser matches less than half of the entities
(its regexes no longer fit the gen format); `--strict` also fails when the
parser cannot be imported.
"""

import argparse
import importlib.util
import re
import sys
from pathlib import Path

REPORT_PATH = Path("logs/type-audit.md")
GEN_DIR = "rankless_rs/src/gen"
GEN_READER = "libs/ccl-science-data/scripts/gen_reader.py"

# The ccl reader only loads array-shaped entities (`type T = u{N}` or
# `Box<[u{N}]>`); complex-T entities are intentionally not loadable, so the
# ground truth is scoped to the same set the parser targets.
_ENTITY_NAME_RE = re.compile(
    r"impl Entity for \w+\s*\{\s*type T = (?:u\d+|Box<\[u\d+\]>);"
    r'[^}]*?const NAME: &\s?str = "([^"]+)";',
    re.DOTALL,
)


def main() -> int:
    ap = argparse.ArgumentParser(description="ccl gen-reader coherence check.")
    ap.add_argument("--strict", action="store_true", help="also fail on warnings.")
    args = ap.parse_args()

    severity, message = audit_gen()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(
        "# Gen reader audit\n\n"
        f"_Generated by `make type-audit`._\n\n- **{severity}** — {message}\n"
    )
    print(f"[type-audit] {severity}: {message} -> {REPORT_PATH}")
    return 1 if severity == "error" or (args.strict and severity == "warn") else 0


def audit_gen() -> tuple[str, str]:
    gen_txt = "\n\n".join(
        p.read_text() for p in sorted(Path(GEN_DIR).iterdir()) if p.suffix == ".rs"
    )
    ground = set(_ENTITY_NAME_RE.findall(gen_txt))
    parse_entities = _import_ccl_parser()
    if parse_entities is None:
        return "warn", f"could not import the ccl parser at {GEN_READER}"
    numents, arrents, _ = parse_entities(gen_txt)
    ccl_names = {en for _, en, _ in [*numents, *arrents]}
    missing = ground - ccl_names
    base = f"ccl parses {len(ccl_names)}/{len(ground)} array entities"
    # A large drop is the drift signature (cargo-fmt reflows `& str` -> `&str`
    # multiline and a brittle regex silently matches nothing). A small residue
    # is structural: entities without a NamespacedEntity impl are unreachable.
    if not ground or len(ccl_names) < len(ground) // 2:
        return "error", (
            f"{base} — the regexes no longer match the gen format. "
            "Fix scripts/gen_reader.py (`&str` / multiline)."
        )
    if missing:
        return "info", (
            f"{base}; {len(missing)} lack a NamespacedEntity impl and aren't "
            f"loadable ({', '.join(sorted(missing))})."
        )
    return "info", f"{base}: all loadable."


def _import_ccl_parser():
    spec = importlib.util.spec_from_file_location("ccl_gen_reader", GEN_READER)
    if spec is None or spec.loader is None:
        return None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._parse_entities


if __name__ == "__main__":
    sys.exit(main())
